<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="PlatformImpl\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Tmds.DBus" Version="0.94.1" />
    </ItemGroup>

</Project>
