<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' And '$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
        <DefineConstants>_WIN_NT;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <DefineConstants>_LINUX;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
        <DefineConstants>_OSX;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Tmds.DBus" Version="0.94.1" />
    </ItemGroup>
</Project>
